// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blend_srgb`, `cache`, `cached_image`, `cached_strip_preprocess`, `crop_srgb`, `display_error`, `elapsed_millis`, `enqueue_export_impl`, `ensure_not_cancelled`, `export_job_work`, `extract_thumb_impl`, `find_manifest`, `fit_dimensions`, `image_pixel`, `import_model_impl`, `job_cancel_flags`, `list_models_impl`, `load_named_model`, `model_cache`, `model_entry_to_bridge`, `new`, `open_image_impl`, `parse_device`, `prepare_denoised_strip_input`, `render_image`, `render_standalone`, `render_strip_reference`, `run_one_strip`, `run_test_strip_impl`, `sample_bilinear_with_grade`, `sample_bilinear`, `send_job_event`, `send_strip_event`, `store_strip_preprocess`, `strip_preprocess_cache`, `strip_preprocess_is_cacheable`, `to_core_rect`, `to_core`, `to_u8`, `validate_region`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CancellableRestorer`, `StripPreprocessCacheEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `run`, `scale`, `tile_hint`

Future<ThumbData> extractThumb({required String path}) =>
    RustLib.instance.api.crateApiSimpleExtractThumb(path: path);

Future<ImageHandle> openImage({
  required String path,
  required double exposureEv,
  double? filmicContrast,
}) => RustLib.instance.api.crateApiSimpleOpenImage(
  path: path,
  exposureEv: exposureEv,
  filmicContrast: filmicContrast,
);

Future<RgbaBytes> renderPreview({
  required ImageHandle handle,
  required int maxEdge,
  required GradeParamsDto grade,
}) => RustLib.instance.api.crateApiSimpleRenderPreview(
  handle: handle,
  maxEdge: maxEdge,
  grade: grade,
);

Future<RgbaBytes> renderRegion({
  required ImageHandle handle,
  required RegionRect rect,
  required int maxEdge,
  required GradeParamsDto grade,
}) => RustLib.instance.api.crateApiSimpleRenderRegion(
  handle: handle,
  rect: rect,
  maxEdge: maxEdge,
  grade: grade,
);

Future<bool> closeImage({required ImageHandle handle}) =>
    RustLib.instance.api.crateApiSimpleCloseImage(handle: handle);

Future<List<ModelEntry>> listModels() =>
    RustLib.instance.api.crateApiSimpleListModels();

Stream<StripEvent> runTestStrip({
  required ImageHandle handle,
  required RegionRect rect,
  required List<String> models,
  String? denoiseModel,
  required GradeParamsDto grade,
}) => RustLib.instance.api.crateApiSimpleRunTestStrip(
  handle: handle,
  rect: rect,
  models: models,
  denoiseModel: denoiseModel,
  grade: grade,
);

Stream<JobEvent> enqueueExport({required ExportJob job}) =>
    RustLib.instance.api.crateApiSimpleEnqueueExport(job: job);

Future<bool> cancelJob({required BigInt jobId}) =>
    RustLib.instance.api.crateApiSimpleCancelJob(jobId: jobId);

Future<ModelEntry> importModel({required ImportModelRequest request}) =>
    RustLib.instance.api.crateApiSimpleImportModel(request: request);

Future<RuntimeInfo> runtimeInfo() =>
    RustLib.instance.api.crateApiSimpleRuntimeInfo();

class ExifData {
  final String make;
  final String model;
  final String? lensModel;
  final int? iso;
  final double? exposureSeconds;
  final double? aperture;
  final double? focalLengthMm;
  final String? capturedAt;
  final int? orientation;

  const ExifData({
    required this.make,
    required this.model,
    this.lensModel,
    this.iso,
    this.exposureSeconds,
    this.aperture,
    this.focalLengthMm,
    this.capturedAt,
    this.orientation,
  });

  @override
  int get hashCode =>
      make.hashCode ^
      model.hashCode ^
      lensModel.hashCode ^
      iso.hashCode ^
      exposureSeconds.hashCode ^
      aperture.hashCode ^
      focalLengthMm.hashCode ^
      capturedAt.hashCode ^
      orientation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExifData &&
          runtimeType == other.runtimeType &&
          make == other.make &&
          model == other.model &&
          lensModel == other.lensModel &&
          iso == other.iso &&
          exposureSeconds == other.exposureSeconds &&
          aperture == other.aperture &&
          focalLengthMm == other.focalLengthMm &&
          capturedAt == other.capturedAt &&
          orientation == other.orientation;
}

class ExportJob {
  final ImageHandle handle;
  final String outputPath;
  final String outputFormat;
  final int? jpegQuality;
  final int? maxOutputEdge;
  final RegionRect? crop;
  final String? denoiseModel;
  final double denoiseStrength;
  final String? srModel;
  final String device;
  final int? tileSize;
  final int? memoryBudgetMib;
  final GradeParamsDto grade;

  const ExportJob({
    required this.handle,
    required this.outputPath,
    required this.outputFormat,
    this.jpegQuality,
    this.maxOutputEdge,
    this.crop,
    this.denoiseModel,
    required this.denoiseStrength,
    this.srModel,
    required this.device,
    this.tileSize,
    this.memoryBudgetMib,
    required this.grade,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      outputPath.hashCode ^
      outputFormat.hashCode ^
      jpegQuality.hashCode ^
      maxOutputEdge.hashCode ^
      crop.hashCode ^
      denoiseModel.hashCode ^
      denoiseStrength.hashCode ^
      srModel.hashCode ^
      device.hashCode ^
      tileSize.hashCode ^
      memoryBudgetMib.hashCode ^
      grade.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportJob &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          outputPath == other.outputPath &&
          outputFormat == other.outputFormat &&
          jpegQuality == other.jpegQuality &&
          maxOutputEdge == other.maxOutputEdge &&
          crop == other.crop &&
          denoiseModel == other.denoiseModel &&
          denoiseStrength == other.denoiseStrength &&
          srModel == other.srModel &&
          device == other.device &&
          tileSize == other.tileSize &&
          memoryBudgetMib == other.memoryBudgetMib &&
          grade == other.grade;
}

class GradeParamsDto {
  final double contrast;
  final double highlights;
  final double shadows;
  final double whites;
  final double blacks;
  final double vibrance;
  final double saturation;

  const GradeParamsDto({
    required this.contrast,
    required this.highlights,
    required this.shadows,
    required this.whites,
    required this.blacks,
    required this.vibrance,
    required this.saturation,
  });

  static Future<GradeParamsDto> default_() =>
      RustLib.instance.api.crateApiSimpleGradeParamsDtoDefault();

  @override
  int get hashCode =>
      contrast.hashCode ^
      highlights.hashCode ^
      shadows.hashCode ^
      whites.hashCode ^
      blacks.hashCode ^
      vibrance.hashCode ^
      saturation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GradeParamsDto &&
          runtimeType == other.runtimeType &&
          contrast == other.contrast &&
          highlights == other.highlights &&
          shadows == other.shadows &&
          whites == other.whites &&
          blacks == other.blacks &&
          vibrance == other.vibrance &&
          saturation == other.saturation;
}

class ImageHandle {
  final BigInt id;
  final int width;
  final int height;

  const ImageHandle({
    required this.id,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => id.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageHandle &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          width == other.width &&
          height == other.height;
}

class ImportModelRequest {
  final String sourcePath;
  final String name;
  final String kind;
  final int scale;
  final int tile;
  final int overlap;
  final String channelOrder;
  final String inputRange;
  final String notes;

  const ImportModelRequest({
    required this.sourcePath,
    required this.name,
    required this.kind,
    required this.scale,
    required this.tile,
    required this.overlap,
    required this.channelOrder,
    required this.inputRange,
    required this.notes,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      scale.hashCode ^
      tile.hashCode ^
      overlap.hashCode ^
      channelOrder.hashCode ^
      inputRange.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportModelRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          name == other.name &&
          kind == other.kind &&
          scale == other.scale &&
          tile == other.tile &&
          overlap == other.overlap &&
          channelOrder == other.channelOrder &&
          inputRange == other.inputRange &&
          notes == other.notes;
}

class JobEvent {
  final BigInt jobId;
  final String state;
  final double progress;
  final String message;
  final String? outputPath;
  final String? reason;

  const JobEvent({
    required this.jobId,
    required this.state,
    required this.progress,
    required this.message,
    this.outputPath,
    this.reason,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      state.hashCode ^
      progress.hashCode ^
      message.hashCode ^
      outputPath.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JobEvent &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          state == other.state &&
          progress == other.progress &&
          message == other.message &&
          outputPath == other.outputPath &&
          reason == other.reason;
}

class ModelEntry {
  final String name;
  final String file;
  final int scale;
  final String kind;
  final int tile;
  final int overlap;
  final String channelOrder;
  final String inputRange;
  final String notes;
  final bool installed;
  final BigInt fileSizeBytes;

  const ModelEntry({
    required this.name,
    required this.file,
    required this.scale,
    required this.kind,
    required this.tile,
    required this.overlap,
    required this.channelOrder,
    required this.inputRange,
    required this.notes,
    required this.installed,
    required this.fileSizeBytes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      file.hashCode ^
      scale.hashCode ^
      kind.hashCode ^
      tile.hashCode ^
      overlap.hashCode ^
      channelOrder.hashCode ^
      inputRange.hashCode ^
      notes.hashCode ^
      installed.hashCode ^
      fileSizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          file == other.file &&
          scale == other.scale &&
          kind == other.kind &&
          tile == other.tile &&
          overlap == other.overlap &&
          channelOrder == other.channelOrder &&
          inputRange == other.inputRange &&
          notes == other.notes &&
          installed == other.installed &&
          fileSizeBytes == other.fileSizeBytes;
}

class ProviderAllocation {
  final String provider;
  final int nodeCount;

  const ProviderAllocation({required this.provider, required this.nodeCount});

  @override
  int get hashCode => provider.hashCode ^ nodeCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderAllocation &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          nodeCount == other.nodeCount;
}

class RegionRect {
  final int x;
  final int y;
  final int width;
  final int height;

  const RegionRect({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegionRect &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height;
}

class RgbaBytes {
  final Uint8List bytes;
  final int width;
  final int height;

  const RgbaBytes({
    required this.bytes,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => bytes.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RgbaBytes &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          width == other.width &&
          height == other.height;
}

class RuntimeInfo {
  final String platform;
  final List<String> compiledProviders;
  final List<ProviderAllocation> lastAllocations;
  final String preferredDevice;

  const RuntimeInfo({
    required this.platform,
    required this.compiledProviders,
    required this.lastAllocations,
    required this.preferredDevice,
  });

  @override
  int get hashCode =>
      platform.hashCode ^
      compiledProviders.hashCode ^
      lastAllocations.hashCode ^
      preferredDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeInfo &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          compiledProviders == other.compiledProviders &&
          lastAllocations == other.lastAllocations &&
          preferredDevice == other.preferredDevice;
}

class StripEvent {
  final String model;
  final bool isReference;
  final String state;
  final double progress;
  final BigInt elapsedMs;
  final RgbaBytes? image;
  final String? reason;

  const StripEvent({
    required this.model,
    required this.isReference,
    required this.state,
    required this.progress,
    required this.elapsedMs,
    this.image,
    this.reason,
  });

  @override
  int get hashCode =>
      model.hashCode ^
      isReference.hashCode ^
      state.hashCode ^
      progress.hashCode ^
      elapsedMs.hashCode ^
      image.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StripEvent &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          isReference == other.isReference &&
          state == other.state &&
          progress == other.progress &&
          elapsedMs == other.elapsedMs &&
          image == other.image &&
          reason == other.reason;
}

class ThumbData {
  final Uint8List jpeg;
  final int width;
  final int height;
  final ExifData exif;

  const ThumbData({
    required this.jpeg,
    required this.width,
    required this.height,
    required this.exif,
  });

  @override
  int get hashCode =>
      jpeg.hashCode ^ width.hashCode ^ height.hashCode ^ exif.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbData &&
          runtimeType == other.runtimeType &&
          jpeg == other.jpeg &&
          width == other.width &&
          height == other.height &&
          exif == other.exif;
}
