// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<JobEvent> dco_decode_StreamSink_job_event_Sse(dynamic raw);

  @protected
  RustStreamSink<StripEvent> dco_decode_StreamSink_strip_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ExportJob dco_decode_box_autoadd_export_job(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  GradeParamsDto dco_decode_box_autoadd_grade_params_dto(dynamic raw);

  @protected
  ImageHandle dco_decode_box_autoadd_image_handle(dynamic raw);

  @protected
  ImportModelRequest dco_decode_box_autoadd_import_model_request(dynamic raw);

  @protected
  RegionRect dco_decode_box_autoadd_region_rect(dynamic raw);

  @protected
  RgbaBytes dco_decode_box_autoadd_rgba_bytes(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ExifData dco_decode_exif_data(dynamic raw);

  @protected
  ExportJob dco_decode_export_job(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GradeParamsDto dco_decode_grade_params_dto(dynamic raw);

  @protected
  ImageHandle dco_decode_image_handle(dynamic raw);

  @protected
  ImportModelRequest dco_decode_import_model_request(dynamic raw);

  @protected
  JobEvent dco_decode_job_event(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ModelEntry> dco_decode_list_model_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProviderAllocation> dco_decode_list_provider_allocation(dynamic raw);

  @protected
  ModelEntry dco_decode_model_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  RegionRect? dco_decode_opt_box_autoadd_region_rect(dynamic raw);

  @protected
  RgbaBytes? dco_decode_opt_box_autoadd_rgba_bytes(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  ProviderAllocation dco_decode_provider_allocation(dynamic raw);

  @protected
  RegionRect dco_decode_region_rect(dynamic raw);

  @protected
  RgbaBytes dco_decode_rgba_bytes(dynamic raw);

  @protected
  RuntimeInfo dco_decode_runtime_info(dynamic raw);

  @protected
  StripEvent dco_decode_strip_event(dynamic raw);

  @protected
  ThumbData dco_decode_thumb_data(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<JobEvent> sse_decode_StreamSink_job_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<StripEvent> sse_decode_StreamSink_strip_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ExportJob sse_decode_box_autoadd_export_job(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  GradeParamsDto sse_decode_box_autoadd_grade_params_dto(
    SseDeserializer deserializer,
  );

  @protected
  ImageHandle sse_decode_box_autoadd_image_handle(SseDeserializer deserializer);

  @protected
  ImportModelRequest sse_decode_box_autoadd_import_model_request(
    SseDeserializer deserializer,
  );

  @protected
  RegionRect sse_decode_box_autoadd_region_rect(SseDeserializer deserializer);

  @protected
  RgbaBytes sse_decode_box_autoadd_rgba_bytes(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ExifData sse_decode_exif_data(SseDeserializer deserializer);

  @protected
  ExportJob sse_decode_export_job(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GradeParamsDto sse_decode_grade_params_dto(SseDeserializer deserializer);

  @protected
  ImageHandle sse_decode_image_handle(SseDeserializer deserializer);

  @protected
  ImportModelRequest sse_decode_import_model_request(
    SseDeserializer deserializer,
  );

  @protected
  JobEvent sse_decode_job_event(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ModelEntry> sse_decode_list_model_entry(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProviderAllocation> sse_decode_list_provider_allocation(
    SseDeserializer deserializer,
  );

  @protected
  ModelEntry sse_decode_model_entry(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  RegionRect? sse_decode_opt_box_autoadd_region_rect(
    SseDeserializer deserializer,
  );

  @protected
  RgbaBytes? sse_decode_opt_box_autoadd_rgba_bytes(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ProviderAllocation sse_decode_provider_allocation(
    SseDeserializer deserializer,
  );

  @protected
  RegionRect sse_decode_region_rect(SseDeserializer deserializer);

  @protected
  RgbaBytes sse_decode_rgba_bytes(SseDeserializer deserializer);

  @protected
  RuntimeInfo sse_decode_runtime_info(SseDeserializer deserializer);

  @protected
  StripEvent sse_decode_strip_event(SseDeserializer deserializer);

  @protected
  ThumbData sse_decode_thumb_data(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_job_event_Sse(
    RustStreamSink<JobEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_strip_event_Sse(
    RustStreamSink<StripEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_export_job(
    ExportJob self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_grade_params_dto(
    GradeParamsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_handle(
    ImageHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_import_model_request(
    ImportModelRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_region_rect(
    RegionRect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rgba_bytes(
    RgbaBytes self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_exif_data(ExifData self, SseSerializer serializer);

  @protected
  void sse_encode_export_job(ExportJob self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_grade_params_dto(
    GradeParamsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_image_handle(ImageHandle self, SseSerializer serializer);

  @protected
  void sse_encode_import_model_request(
    ImportModelRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_job_event(JobEvent self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_model_entry(
    List<ModelEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_allocation(
    List<ProviderAllocation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_entry(ModelEntry self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_region_rect(
    RegionRect? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rgba_bytes(
    RgbaBytes? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_provider_allocation(
    ProviderAllocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_region_rect(RegionRect self, SseSerializer serializer);

  @protected
  void sse_encode_rgba_bytes(RgbaBytes self, SseSerializer serializer);

  @protected
  void sse_encode_runtime_info(RuntimeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_strip_event(StripEvent self, SseSerializer serializer);

  @protected
  void sse_encode_thumb_data(ThumbData self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
