// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1360241032;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rawsr_bridge',
        ioDirectory: '../crates/rawsr-bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiSimpleCancelJob({required BigInt jobId});

  Future<bool> crateApiSimpleCloseImage({required ImageHandle handle});

  Stream<JobEvent> crateApiSimpleEnqueueExport({required ExportJob job});

  Future<ThumbData> crateApiSimpleExtractThumb({required String path});

  Future<GradeParamsDto> crateApiSimpleGradeParamsDtoDefault();

  Future<ModelEntry> crateApiSimpleImportModel({
    required ImportModelRequest request,
  });

  Future<void> crateApiSimpleInitApp();

  Future<List<ModelEntry>> crateApiSimpleListModels();

  Future<ImageHandle> crateApiSimpleOpenImage({
    required String path,
    required double exposureEv,
    double? filmicContrast,
  });

  Future<RgbaBytes> crateApiSimpleRenderPreview({
    required ImageHandle handle,
    required int maxEdge,
    required GradeParamsDto grade,
  });

  Future<RgbaBytes> crateApiSimpleRenderRegion({
    required ImageHandle handle,
    required RegionRect rect,
    required int maxEdge,
    required GradeParamsDto grade,
  });

  Stream<StripEvent> crateApiSimpleRunTestStrip({
    required ImageHandle handle,
    required RegionRect rect,
    required List<String> models,
    String? denoiseModel,
    required GradeParamsDto grade,
  });

  Future<RuntimeInfo> crateApiSimpleRuntimeInfo();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiSimpleCancelJob({required BigInt jobId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(jobId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCancelJobConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCancelJobConstMeta =>
      const TaskConstMeta(debugName: "cancel_job", argNames: ["jobId"]);

  @override
  Future<bool> crateApiSimpleCloseImage({required ImageHandle handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_image_handle(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCloseImageConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCloseImageConstMeta =>
      const TaskConstMeta(debugName: "close_image", argNames: ["handle"]);

  @override
  Stream<JobEvent> crateApiSimpleEnqueueExport({required ExportJob job}) {
    final sink = RustStreamSink<JobEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_export_job(job, serializer);
            sse_encode_StreamSink_job_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSimpleEnqueueExportConstMeta,
          argValues: [job, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleEnqueueExportConstMeta =>
      const TaskConstMeta(
        debugName: "enqueue_export",
        argNames: ["job", "sink"],
      );

  @override
  Future<ThumbData> crateApiSimpleExtractThumb({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_thumb_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleExtractThumbConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleExtractThumbConstMeta =>
      const TaskConstMeta(debugName: "extract_thumb", argNames: ["path"]);

  @override
  Future<GradeParamsDto> crateApiSimpleGradeParamsDtoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_grade_params_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGradeParamsDtoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGradeParamsDtoDefaultConstMeta =>
      const TaskConstMeta(debugName: "grade_params_dto_default", argNames: []);

  @override
  Future<ModelEntry> crateApiSimpleImportModel({
    required ImportModelRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_import_model_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_model_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleImportModelConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportModelConstMeta =>
      const TaskConstMeta(debugName: "import_model", argNames: ["request"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<ModelEntry>> crateApiSimpleListModels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_model_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleListModelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListModelsConstMeta =>
      const TaskConstMeta(debugName: "list_models", argNames: []);

  @override
  Future<ImageHandle> crateApiSimpleOpenImage({
    required String path,
    required double exposureEv,
    double? filmicContrast,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_f_32(exposureEv, serializer);
          sse_encode_opt_box_autoadd_f_32(filmicContrast, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_handle,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleOpenImageConstMeta,
        argValues: [path, exposureEv, filmicContrast],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleOpenImageConstMeta => const TaskConstMeta(
    debugName: "open_image",
    argNames: ["path", "exposureEv", "filmicContrast"],
  );

  @override
  Future<RgbaBytes> crateApiSimpleRenderPreview({
    required ImageHandle handle,
    required int maxEdge,
    required GradeParamsDto grade,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_image_handle(handle, serializer);
          sse_encode_u_32(maxEdge, serializer);
          sse_encode_box_autoadd_grade_params_dto(grade, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rgba_bytes,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleRenderPreviewConstMeta,
        argValues: [handle, maxEdge, grade],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRenderPreviewConstMeta =>
      const TaskConstMeta(
        debugName: "render_preview",
        argNames: ["handle", "maxEdge", "grade"],
      );

  @override
  Future<RgbaBytes> crateApiSimpleRenderRegion({
    required ImageHandle handle,
    required RegionRect rect,
    required int maxEdge,
    required GradeParamsDto grade,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_image_handle(handle, serializer);
          sse_encode_box_autoadd_region_rect(rect, serializer);
          sse_encode_u_32(maxEdge, serializer);
          sse_encode_box_autoadd_grade_params_dto(grade, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rgba_bytes,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleRenderRegionConstMeta,
        argValues: [handle, rect, maxEdge, grade],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRenderRegionConstMeta => const TaskConstMeta(
    debugName: "render_region",
    argNames: ["handle", "rect", "maxEdge", "grade"],
  );

  @override
  Stream<StripEvent> crateApiSimpleRunTestStrip({
    required ImageHandle handle,
    required RegionRect rect,
    required List<String> models,
    String? denoiseModel,
    required GradeParamsDto grade,
  }) {
    final sink = RustStreamSink<StripEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_image_handle(handle, serializer);
            sse_encode_box_autoadd_region_rect(rect, serializer);
            sse_encode_list_String(models, serializer);
            sse_encode_opt_String(denoiseModel, serializer);
            sse_encode_box_autoadd_grade_params_dto(grade, serializer);
            sse_encode_StreamSink_strip_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 12,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSimpleRunTestStripConstMeta,
          argValues: [handle, rect, models, denoiseModel, grade, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleRunTestStripConstMeta => const TaskConstMeta(
    debugName: "run_test_strip",
    argNames: ["handle", "rect", "models", "denoiseModel", "grade", "sink"],
  );

  @override
  Future<RuntimeInfo> crateApiSimpleRuntimeInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_runtime_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRuntimeInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRuntimeInfoConstMeta =>
      const TaskConstMeta(debugName: "runtime_info", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<JobEvent> dco_decode_StreamSink_job_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<StripEvent> dco_decode_StreamSink_strip_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ExportJob dco_decode_box_autoadd_export_job(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_export_job(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GradeParamsDto dco_decode_box_autoadd_grade_params_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_grade_params_dto(raw);
  }

  @protected
  ImageHandle dco_decode_box_autoadd_image_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_handle(raw);
  }

  @protected
  ImportModelRequest dco_decode_box_autoadd_import_model_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_import_model_request(raw);
  }

  @protected
  RegionRect dco_decode_box_autoadd_region_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_region_rect(raw);
  }

  @protected
  RgbaBytes dco_decode_box_autoadd_rgba_bytes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rgba_bytes(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ExifData dco_decode_exif_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ExifData(
      make: dco_decode_String(arr[0]),
      model: dco_decode_String(arr[1]),
      lensModel: dco_decode_opt_String(arr[2]),
      iso: dco_decode_opt_box_autoadd_u_32(arr[3]),
      exposureSeconds: dco_decode_opt_box_autoadd_f_32(arr[4]),
      aperture: dco_decode_opt_box_autoadd_f_32(arr[5]),
      focalLengthMm: dco_decode_opt_box_autoadd_f_32(arr[6]),
      capturedAt: dco_decode_opt_String(arr[7]),
      orientation: dco_decode_opt_box_autoadd_u_16(arr[8]),
    );
  }

  @protected
  ExportJob dco_decode_export_job(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return ExportJob(
      handle: dco_decode_image_handle(arr[0]),
      outputPath: dco_decode_String(arr[1]),
      outputFormat: dco_decode_String(arr[2]),
      jpegQuality: dco_decode_opt_box_autoadd_u_32(arr[3]),
      maxOutputEdge: dco_decode_opt_box_autoadd_u_32(arr[4]),
      crop: dco_decode_opt_box_autoadd_region_rect(arr[5]),
      denoiseModel: dco_decode_opt_String(arr[6]),
      denoiseStrength: dco_decode_f_32(arr[7]),
      srModel: dco_decode_opt_String(arr[8]),
      device: dco_decode_String(arr[9]),
      tileSize: dco_decode_opt_box_autoadd_u_32(arr[10]),
      memoryBudgetMib: dco_decode_opt_box_autoadd_u_32(arr[11]),
      grade: dco_decode_grade_params_dto(arr[12]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GradeParamsDto dco_decode_grade_params_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return GradeParamsDto(
      contrast: dco_decode_f_32(arr[0]),
      highlights: dco_decode_f_32(arr[1]),
      shadows: dco_decode_f_32(arr[2]),
      whites: dco_decode_f_32(arr[3]),
      blacks: dco_decode_f_32(arr[4]),
      vibrance: dco_decode_f_32(arr[5]),
      saturation: dco_decode_f_32(arr[6]),
    );
  }

  @protected
  ImageHandle dco_decode_image_handle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ImageHandle(
      id: dco_decode_u_64(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  ImportModelRequest dco_decode_import_model_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ImportModelRequest(
      sourcePath: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      scale: dco_decode_u_32(arr[3]),
      tile: dco_decode_u_32(arr[4]),
      overlap: dco_decode_u_32(arr[5]),
      channelOrder: dco_decode_String(arr[6]),
      inputRange: dco_decode_String(arr[7]),
      notes: dco_decode_String(arr[8]),
    );
  }

  @protected
  JobEvent dco_decode_job_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return JobEvent(
      jobId: dco_decode_u_64(arr[0]),
      state: dco_decode_String(arr[1]),
      progress: dco_decode_f_32(arr[2]),
      message: dco_decode_String(arr[3]),
      outputPath: dco_decode_opt_String(arr[4]),
      reason: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ModelEntry> dco_decode_list_model_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProviderAllocation> dco_decode_list_provider_allocation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_provider_allocation).toList();
  }

  @protected
  ModelEntry dco_decode_model_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ModelEntry(
      name: dco_decode_String(arr[0]),
      file: dco_decode_String(arr[1]),
      scale: dco_decode_u_32(arr[2]),
      kind: dco_decode_String(arr[3]),
      tile: dco_decode_u_32(arr[4]),
      overlap: dco_decode_u_32(arr[5]),
      channelOrder: dco_decode_String(arr[6]),
      inputRange: dco_decode_String(arr[7]),
      notes: dco_decode_String(arr[8]),
      installed: dco_decode_bool(arr[9]),
      fileSizeBytes: dco_decode_u_64(arr[10]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  RegionRect? dco_decode_opt_box_autoadd_region_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_region_rect(raw);
  }

  @protected
  RgbaBytes? dco_decode_opt_box_autoadd_rgba_bytes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_rgba_bytes(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  ProviderAllocation dco_decode_provider_allocation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ProviderAllocation(
      provider: dco_decode_String(arr[0]),
      nodeCount: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  RegionRect dco_decode_region_rect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RegionRect(
      x: dco_decode_u_32(arr[0]),
      y: dco_decode_u_32(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  RgbaBytes dco_decode_rgba_bytes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RgbaBytes(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  RuntimeInfo dco_decode_runtime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RuntimeInfo(
      platform: dco_decode_String(arr[0]),
      compiledProviders: dco_decode_list_String(arr[1]),
      lastAllocations: dco_decode_list_provider_allocation(arr[2]),
      preferredDevice: dco_decode_String(arr[3]),
    );
  }

  @protected
  StripEvent dco_decode_strip_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return StripEvent(
      model: dco_decode_String(arr[0]),
      isReference: dco_decode_bool(arr[1]),
      state: dco_decode_String(arr[2]),
      progress: dco_decode_f_32(arr[3]),
      elapsedMs: dco_decode_u_64(arr[4]),
      image: dco_decode_opt_box_autoadd_rgba_bytes(arr[5]),
      reason: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  ThumbData dco_decode_thumb_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ThumbData(
      jpeg: dco_decode_list_prim_u_8_strict(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      exif: dco_decode_exif_data(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<JobEvent> sse_decode_StreamSink_job_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<StripEvent> sse_decode_StreamSink_strip_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ExportJob sse_decode_box_autoadd_export_job(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_export_job(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  GradeParamsDto sse_decode_box_autoadd_grade_params_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_grade_params_dto(deserializer));
  }

  @protected
  ImageHandle sse_decode_box_autoadd_image_handle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_handle(deserializer));
  }

  @protected
  ImportModelRequest sse_decode_box_autoadd_import_model_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_import_model_request(deserializer));
  }

  @protected
  RegionRect sse_decode_box_autoadd_region_rect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_region_rect(deserializer));
  }

  @protected
  RgbaBytes sse_decode_box_autoadd_rgba_bytes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rgba_bytes(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  ExifData sse_decode_exif_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_make = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_lensModel = sse_decode_opt_String(deserializer);
    var var_iso = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_exposureSeconds = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_aperture = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_focalLengthMm = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_capturedAt = sse_decode_opt_String(deserializer);
    var var_orientation = sse_decode_opt_box_autoadd_u_16(deserializer);
    return ExifData(
      make: var_make,
      model: var_model,
      lensModel: var_lensModel,
      iso: var_iso,
      exposureSeconds: var_exposureSeconds,
      aperture: var_aperture,
      focalLengthMm: var_focalLengthMm,
      capturedAt: var_capturedAt,
      orientation: var_orientation,
    );
  }

  @protected
  ExportJob sse_decode_export_job(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_image_handle(deserializer);
    var var_outputPath = sse_decode_String(deserializer);
    var var_outputFormat = sse_decode_String(deserializer);
    var var_jpegQuality = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_maxOutputEdge = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_crop = sse_decode_opt_box_autoadd_region_rect(deserializer);
    var var_denoiseModel = sse_decode_opt_String(deserializer);
    var var_denoiseStrength = sse_decode_f_32(deserializer);
    var var_srModel = sse_decode_opt_String(deserializer);
    var var_device = sse_decode_String(deserializer);
    var var_tileSize = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_memoryBudgetMib = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_grade = sse_decode_grade_params_dto(deserializer);
    return ExportJob(
      handle: var_handle,
      outputPath: var_outputPath,
      outputFormat: var_outputFormat,
      jpegQuality: var_jpegQuality,
      maxOutputEdge: var_maxOutputEdge,
      crop: var_crop,
      denoiseModel: var_denoiseModel,
      denoiseStrength: var_denoiseStrength,
      srModel: var_srModel,
      device: var_device,
      tileSize: var_tileSize,
      memoryBudgetMib: var_memoryBudgetMib,
      grade: var_grade,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  GradeParamsDto sse_decode_grade_params_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_contrast = sse_decode_f_32(deserializer);
    var var_highlights = sse_decode_f_32(deserializer);
    var var_shadows = sse_decode_f_32(deserializer);
    var var_whites = sse_decode_f_32(deserializer);
    var var_blacks = sse_decode_f_32(deserializer);
    var var_vibrance = sse_decode_f_32(deserializer);
    var var_saturation = sse_decode_f_32(deserializer);
    return GradeParamsDto(
      contrast: var_contrast,
      highlights: var_highlights,
      shadows: var_shadows,
      whites: var_whites,
      blacks: var_blacks,
      vibrance: var_vibrance,
      saturation: var_saturation,
    );
  }

  @protected
  ImageHandle sse_decode_image_handle(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return ImageHandle(id: var_id, width: var_width, height: var_height);
  }

  @protected
  ImportModelRequest sse_decode_import_model_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_scale = sse_decode_u_32(deserializer);
    var var_tile = sse_decode_u_32(deserializer);
    var var_overlap = sse_decode_u_32(deserializer);
    var var_channelOrder = sse_decode_String(deserializer);
    var var_inputRange = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    return ImportModelRequest(
      sourcePath: var_sourcePath,
      name: var_name,
      kind: var_kind,
      scale: var_scale,
      tile: var_tile,
      overlap: var_overlap,
      channelOrder: var_channelOrder,
      inputRange: var_inputRange,
      notes: var_notes,
    );
  }

  @protected
  JobEvent sse_decode_job_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_jobId = sse_decode_u_64(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_opt_String(deserializer);
    var var_reason = sse_decode_opt_String(deserializer);
    return JobEvent(
      jobId: var_jobId,
      state: var_state,
      progress: var_progress,
      message: var_message,
      outputPath: var_outputPath,
      reason: var_reason,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelEntry> sse_decode_list_model_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProviderAllocation> sse_decode_list_provider_allocation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProviderAllocation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_provider_allocation(deserializer));
    }
    return ans_;
  }

  @protected
  ModelEntry sse_decode_model_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_file = sse_decode_String(deserializer);
    var var_scale = sse_decode_u_32(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_tile = sse_decode_u_32(deserializer);
    var var_overlap = sse_decode_u_32(deserializer);
    var var_channelOrder = sse_decode_String(deserializer);
    var var_inputRange = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_installed = sse_decode_bool(deserializer);
    var var_fileSizeBytes = sse_decode_u_64(deserializer);
    return ModelEntry(
      name: var_name,
      file: var_file,
      scale: var_scale,
      kind: var_kind,
      tile: var_tile,
      overlap: var_overlap,
      channelOrder: var_channelOrder,
      inputRange: var_inputRange,
      notes: var_notes,
      installed: var_installed,
      fileSizeBytes: var_fileSizeBytes,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RegionRect? sse_decode_opt_box_autoadd_region_rect(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_region_rect(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RgbaBytes? sse_decode_opt_box_autoadd_rgba_bytes(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_rgba_bytes(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProviderAllocation sse_decode_provider_allocation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_provider = sse_decode_String(deserializer);
    var var_nodeCount = sse_decode_u_32(deserializer);
    return ProviderAllocation(provider: var_provider, nodeCount: var_nodeCount);
  }

  @protected
  RegionRect sse_decode_region_rect(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_u_32(deserializer);
    var var_y = sse_decode_u_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return RegionRect(x: var_x, y: var_y, width: var_width, height: var_height);
  }

  @protected
  RgbaBytes sse_decode_rgba_bytes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return RgbaBytes(bytes: var_bytes, width: var_width, height: var_height);
  }

  @protected
  RuntimeInfo sse_decode_runtime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_platform = sse_decode_String(deserializer);
    var var_compiledProviders = sse_decode_list_String(deserializer);
    var var_lastAllocations = sse_decode_list_provider_allocation(deserializer);
    var var_preferredDevice = sse_decode_String(deserializer);
    return RuntimeInfo(
      platform: var_platform,
      compiledProviders: var_compiledProviders,
      lastAllocations: var_lastAllocations,
      preferredDevice: var_preferredDevice,
    );
  }

  @protected
  StripEvent sse_decode_strip_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_model = sse_decode_String(deserializer);
    var var_isReference = sse_decode_bool(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_32(deserializer);
    var var_elapsedMs = sse_decode_u_64(deserializer);
    var var_image = sse_decode_opt_box_autoadd_rgba_bytes(deserializer);
    var var_reason = sse_decode_opt_String(deserializer);
    return StripEvent(
      model: var_model,
      isReference: var_isReference,
      state: var_state,
      progress: var_progress,
      elapsedMs: var_elapsedMs,
      image: var_image,
      reason: var_reason,
    );
  }

  @protected
  ThumbData sse_decode_thumb_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_jpeg = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_exif = sse_decode_exif_data(deserializer);
    return ThumbData(
      jpeg: var_jpeg,
      width: var_width,
      height: var_height,
      exif: var_exif,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_job_event_Sse(
    RustStreamSink<JobEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_job_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_strip_event_Sse(
    RustStreamSink<StripEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_strip_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_export_job(
    ExportJob self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_job(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_grade_params_dto(
    GradeParamsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_grade_params_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_image_handle(
    ImageHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_handle(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_import_model_request(
    ImportModelRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_import_model_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_region_rect(
    RegionRect self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_region_rect(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rgba_bytes(
    RgbaBytes self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rgba_bytes(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_exif_data(ExifData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.make, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_opt_String(self.lensModel, serializer);
    sse_encode_opt_box_autoadd_u_32(self.iso, serializer);
    sse_encode_opt_box_autoadd_f_32(self.exposureSeconds, serializer);
    sse_encode_opt_box_autoadd_f_32(self.aperture, serializer);
    sse_encode_opt_box_autoadd_f_32(self.focalLengthMm, serializer);
    sse_encode_opt_String(self.capturedAt, serializer);
    sse_encode_opt_box_autoadd_u_16(self.orientation, serializer);
  }

  @protected
  void sse_encode_export_job(ExportJob self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_handle(self.handle, serializer);
    sse_encode_String(self.outputPath, serializer);
    sse_encode_String(self.outputFormat, serializer);
    sse_encode_opt_box_autoadd_u_32(self.jpegQuality, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxOutputEdge, serializer);
    sse_encode_opt_box_autoadd_region_rect(self.crop, serializer);
    sse_encode_opt_String(self.denoiseModel, serializer);
    sse_encode_f_32(self.denoiseStrength, serializer);
    sse_encode_opt_String(self.srModel, serializer);
    sse_encode_String(self.device, serializer);
    sse_encode_opt_box_autoadd_u_32(self.tileSize, serializer);
    sse_encode_opt_box_autoadd_u_32(self.memoryBudgetMib, serializer);
    sse_encode_grade_params_dto(self.grade, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_grade_params_dto(
    GradeParamsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.contrast, serializer);
    sse_encode_f_32(self.highlights, serializer);
    sse_encode_f_32(self.shadows, serializer);
    sse_encode_f_32(self.whites, serializer);
    sse_encode_f_32(self.blacks, serializer);
    sse_encode_f_32(self.vibrance, serializer);
    sse_encode_f_32(self.saturation, serializer);
  }

  @protected
  void sse_encode_image_handle(ImageHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_import_model_request(
    ImportModelRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_u_32(self.scale, serializer);
    sse_encode_u_32(self.tile, serializer);
    sse_encode_u_32(self.overlap, serializer);
    sse_encode_String(self.channelOrder, serializer);
    sse_encode_String(self.inputRange, serializer);
    sse_encode_String(self.notes, serializer);
  }

  @protected
  void sse_encode_job_event(JobEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.jobId, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_f_32(self.progress, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.outputPath, serializer);
    sse_encode_opt_String(self.reason, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_entry(
    List<ModelEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_provider_allocation(
    List<ProviderAllocation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_provider_allocation(item, serializer);
    }
  }

  @protected
  void sse_encode_model_entry(ModelEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.file, serializer);
    sse_encode_u_32(self.scale, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_u_32(self.tile, serializer);
    sse_encode_u_32(self.overlap, serializer);
    sse_encode_String(self.channelOrder, serializer);
    sse_encode_String(self.inputRange, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_bool(self.installed, serializer);
    sse_encode_u_64(self.fileSizeBytes, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_region_rect(
    RegionRect? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_region_rect(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_rgba_bytes(
    RgbaBytes? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_rgba_bytes(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_provider_allocation(
    ProviderAllocation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.provider, serializer);
    sse_encode_u_32(self.nodeCount, serializer);
  }

  @protected
  void sse_encode_region_rect(RegionRect self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.x, serializer);
    sse_encode_u_32(self.y, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_rgba_bytes(RgbaBytes self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_runtime_info(RuntimeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.platform, serializer);
    sse_encode_list_String(self.compiledProviders, serializer);
    sse_encode_list_provider_allocation(self.lastAllocations, serializer);
    sse_encode_String(self.preferredDevice, serializer);
  }

  @protected
  void sse_encode_strip_event(StripEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.model, serializer);
    sse_encode_bool(self.isReference, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_f_32(self.progress, serializer);
    sse_encode_u_64(self.elapsedMs, serializer);
    sse_encode_opt_box_autoadd_rgba_bytes(self.image, serializer);
    sse_encode_opt_String(self.reason, serializer);
  }

  @protected
  void sse_encode_thumb_data(ThumbData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.jpeg, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_exif_data(self.exif, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
